org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.20
forge_version_range=[47.4.20,48)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

java_version=17
mod_id=miniutility
mod_name=Miniutility
mod_license=MIT
mod_version=1.20.1-47.4.20-1.0.0
mod_group_id=org.hotamachisubaru
mod_authors=hotamachisubaru
mod_description=Miniutility for Forge 1.20.1.

luckperms_version=5.5
sqlite_version=3.51.3.0
