name: Maven 継続的インテグレーション

on:
  pull_request:
    branches: [ "master", "main", "forge" ]
  push:
    branches: [ "master", "main", "forge" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: JDK 25 を設定
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "25"
          cache: "maven"
      - name: Maven でビルド
        run: mvn -B -DskipTests verify
      - name: テストを実行
        run: mvn -B test
